# Generated by Django 4.1.3 on 2023-02-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.IntegerField(default=0),
        ),
    ]
