# Generated by Django 4.1.3 on 2023-03-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField(default=0)),
                ('post_id', models.IntegerField(default=0)),
                ('text', models.TextField(default='None', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Views',
        ),
    ]
